### ISSUE TITLE
%na% Missing During Test

### ISSUE THREAD

**Issue by DarioS** [PapenfussLab/StructuralVariantAnnotation#15]
```
$test/gridss_annotate_insertions_repeatmaster.R --input $test/LS13anno.vcf --output $test/LS13annoRetro.vcf --repeatmasker $test/hg38.fa.out.gz --scriptdir $test/
```

results in

```
Loading required package: BSgenome
Error: Test failed: '.linked_assemblies_fix_indels corrects indels'
* could not find function "%na%"
```

**Comment by d-cameron** [comment]
We are in the process of submitting the StructuralVariantAnnotation package
to BioConductor and as part of that process, we have removed some of the
functionality that does not belong in the package (such as %na%). Please
use the following version while we make this transition:

devtools::install_github("PapenfussLab/StructuralVariantAnnotation@pre_bioconductor
")
