### ISSUE TITLE
Installation error related to R version

### ISSUE THREAD

**Issue by tgong1** [PapenfussLab/StructuralVariantAnnotation#16]
Hi, This is the error I got when I try to install the package by install_github("PapenfussLab/StructuralVariantAnnotation"):
ERROR: this R is version 3.5.1, package 'StructuralVariantAnnotation'  requires R >= 3.6.0

I previously installed it on R 3.4.1 and didn't encountered this.
Did I miss anything?

Thank you!

**Comment by d-cameron** [comment]
We are in the process of converting into a BioConductor package and the next release of BioConductor requires R 3.6.0.

Please use the pre_bioconductor branch (`install_github("PapenfussLab/StructuralVariantAnnotation", ref="pre_bioconductor")` ) while we are in this transition period.
