### ISSUE TITLE
Getting this annotation for manta .vcf

### ISSUE THREAD

**Issue by beginner984** [PapenfussLab/StructuralVariantAnnotation#17]
Hi,

I have called SV by Manta, how I could get this specific formats for my .vcf files please?

I have attached a sample .vcf and a desired annotation

[LP2000104-DNA_A01_vs_LP2000101-DNA_A01.SVannotated.txt](https://github.com/PapenfussLab/StructuralVariantAnnotation/files/3108461/LP2000104-DNA_A01_vs_LP2000101-DNA_A01.SVannotated.txt)

[candidateSV.vcf.gz](https://github.com/PapenfussLab/StructuralVariantAnnotation/files/3108466/candidateSV.vcf.gz)

I have been given a ruby script to convert .vcf to BEDEP then R script to get this annotation but I am very bad in coding

So, I am wondering if I could get this annotation at all

**Comment by d-cameron** [comment]
If you already have a script to do this, why not just run that script?

> I have been given a ruby script to convert .vcf to BEDEP

`StructuralVariantAnnotation` can do this entirely in R.

```
vcf = readVcf("candidateSV.vcf.gz`)
bpgr = breakpointRanges(vcf)
```

> R script to get this annotation

 - Score, filters, read counts, can be extracted using `info(vcf)`
 - ME/FS annotation can be loaded as GRanges objects, then all you need to do is call `findOverlaps()` on the breakpoint GRanges object. Something like:

```
bpgr$MobileElement = ""
hits = findOverlaps(bpgr, me_gr, ignore.strand=TRUE)
bpgr$MobileElement [queryHits(hits)] = me_gr[subjectHits(hits)]$mobile_element_annotation
```

- Gene fusion and disruptions are more complicated and actually fairly difficult to get correct. I am intending to add this functionality to `StraucturalVariantAnntoation` in a future release.

> I am very bad in coding

Everyone was bad when the first started. Keep learning :)

**Comment by beginner984** [comment]
Sorry to be this much silly

I have been asked to visualize SV data; You please imagine I have a tumor and its matched model (organoid). I have called SV by Manta (my .vcf files are here)

https://www.dropbox.com/s/mhr63rn6v0fx89k/t_005.vcf?dl=0

https://www.dropbox.com/s/80o836njwgnw81k/o_005.vcf?dl=0

How I can get this picture from this paper 

https://journals.plos.org/ploscompbiol/article?id=10.1371/journal.pcbi.1006596

![journal pcbi 1006596 g005](https://user-images.githubusercontent.com/43682980/56754429-ed887d80-6784-11e9-9b77-b461c3e1a8da.PNG)

 Even code for producing this picture is here 

https://github.com/DGendoo/PDACDiseaseModels/tree/master/SV/PrimaryPairs

But I don't know how use these scripts to produce such picture of my .vcf files

Could you please help me?

**Comment by d-cameron** [comment]
As issue does not involve a bug, feature request, or documentation issue with the StructuralVariantAnntoation package, this issues list is not the appropriate location for this question. Whilst I disagree with the approach to SV analysis taken in that paper, I consider that the complexity of analysis and the depth of understand required to produce the figure you have shown sufficient to warrant an authorship position on the paper in question. That said, just blinding reproducing the same figure on different data is more straight-forward but by no means trivial. I recommend you break the figure down into each component and tackle these one at a time, starting with panels A and B.

This question is much better suited to biostars.org or seqanswers.com
