### ISSUE TITLE
Manta VCF: error in drawing circos plot

### ISSUE THREAD

**Issue by TendoLiu** [PapenfussLab/StructuralVariantAnnotation#24]
Hi, I am currently using this package to draw a circos plot using a vcf file produced by Manta.

colo829_vcf <- VariantAnnotation::readVcf("Manta.vcf.gz")
colo829_bpgr <- breakpointRanges(colo829_vcf)
colo829_begr <- breakendRanges(colo829_vcf)
suppressPackageStartupMessages(require(circlize))
colo829_bpgr_with_chr_prefix <- colo829_bpgr
seqlevelsStyle(colo829_bpgr_with_chr_prefix) <- "UCSC"
pairs <- breakpointgr2pairs(colo829_bpgr_with_chr_prefix)
view(show(pairs))
circos.initializeWithIdeogram()
circos.genomicLink(as.data.frame(S4Vectors::first(pairs)), as.data.frame(S4Vectors::second(pairs)))

Error in circos.genomicLink(as.data.frame(S4Vectors::first(pairs)), as.data.frame(S4Vectors::second(pairs))) : 
  nrow of `region1` and `region2` differ.

Not sure where this message come from and how to solve it.
Manta VCF file
[Manta.vcf.gz](https://github.com/PapenfussLab/StructuralVariantAnnotation/files/3810755/Manta.vcf.gz)

**Comment by TendoLiu** [comment]
Original file
[Manta.vcf.gz](https://github.com/PapenfussLab/StructuralVariantAnnotation/files/3810750/Manta.vcf.gz)

**Comment by d-cameron** [comment]
Not an issue with StructuralVariantAnnotation.
circos.genomicLink() strips your chr11_gl000202_random breakend (presumably because it's not in your circos reference).
