### ISSUE TITLE
Missing %na% function in Bioconductor release version

### ISSUE THREAD

**Issue by roelj** [PapenfussLab/StructuralVariantAnnotation#28]
I'm using GRIDSS 1.8.1 as part of HMF's pipeline v4.8.

In the `gridss_somatic_filter.R` script, there's a call to `gridss_breakpoint_filter`, which calls `is_small_inversion_with_homology`.  That function uses the `%na%` function.

When using the Bioconductor version of StructuralVariantAnnotation, this function cannot be found.  When using the latest version from this Github, the function can be found.

**Comment by d-cameron** [comment]
`%na%` was removed from the `StructuralVariantAnnotation` package as it was a util function not related to structural variants. You'll need install the StructuralVariantAnnotation package from from the `prebioconductor` branch of github.com/PapenfussLab/StructuralVariantAnnotation using `devtools::install_github` or update to a more recent HMF pipline release.

**Comment by d-cameron** [comment]
`%na%` is now package-private in StructuralVariantAnnotation, and also included in `libgridss.R` in recent GRIDSS releases.
