### ISSUE TITLE
Retrotransposed Transcripts and Mitochondrial Fusions Functions Missing from Bioconductor Download

### ISSUE THREAD

**Issue by DarioS** [PapenfussLab/StructuralVariantAnnotation#32]
I installed using `install("StructuralVariantAnnotation")` and installed version 1.6.0. But, it's missing `rtDetect` and `numtDetect`. NEWS file contains only:
```
Changes in version 0.99.0 (2019-04-05)
+ Submitted to BioConductor
```
so it's unclear to the end-user why this functionality was recently removed from the package. Does LINX supersede it?

**Comment by d-cameron** [comment]
They got pulled out into their own package.

@jackieduckie: what's the status on the refactoring. Are they in BioConductor yet?

**Comment by jackieduckie** [comment]
They are under revision and will be made publicly available soon.

**Comment by DarioS** [comment]
Any plans for retrotransposon annotation, such as T.S.D. or source and destination coordinates based on transduction sequences?

**Comment by jackieduckie** [comment]
@DarioS RTDetect should be submitted to BioConductor as a seperate package within a few weeks time. Hope that helps.
