### ISSUE TITLE
Bioconductor Forum Not Monitored

### ISSUE THREAD

**Issue by DarioS** [PapenfussLab/StructuralVariantAnnotation#40]
I asked [a question](https://support.bioconductor.org/p/9143265/) three weeks ago, but there have been no replies. The forum is an integral part of Bioconductor.

![image](https://user-images.githubusercontent.com/631218/165694909-7b16d0a2-07c2-4f52-b37e-8c911180c786.png)

Now that Daniel Cameron is departed from the academic life, how could timely support for StructuralVariantAnnotation continue?

**Comment by d-cameron** [comment]
I don't appear to have gotten the `StructuralVariantAnnotation` email alert for that thread. I've updated my bioconductor support account so hopefully I'll get the next SVA post.
