### ISSUE TITLE
Version compatible with R 3.6?

### ISSUE THREAD

**Issue by pauline-ng** [PapenfussLab/StructuralVariantAnnotation#42]
Hi,

I'm getting the following error:
`ERROR: this R is version 3.6.3, package 'StructuralVariantAnnotation'  requires R >= 4.1.0`

Is there a version of StructuralVariantAnnotation that works with R v3.6?

Thanks

**Comment by d-cameron** [comment]
Yes (e.g. `devtools::install_github("PapenfussLab/StructuralVariantAnnotation", ref="pre_bioconductor")` ) but you'll need to appropriate version of BioConductor for R 3.6 because of the dependencies on other bioconductor package.

**Comment by pauline-ng** [comment]
I finally got a working dockerfile. This took me a while, so I'm putting it here in case others find it helpful.

```
FROM rocker/r-ver:4.0.2

RUN apt-get update && \
    apt-get -y install zlib1g-dev \
    libxml2 \
    libbz2-dev \
    liblzma-dev \
    libcurl4-openssl-dev vim \
    python3.7 python3-pip python3-setuptools

RUN R -e "install.packages('stringr')"

RUN R -e 'install.packages("https://cran.r-project.org/src/contrib/Archive/BiocManager/BiocManager_1.30.10.tar.gz",repos = NULL,type  = "source")' && \
        R -e 'install.packages("https://cran.r-project.org/src/contrib/Archive/matrixStats/matrixStats_0.60.0.tar.gz", repos=NULL, type="source")' && \
        R -e 'BiocManager::install("VariantAnnotation", version="3.12")' && \
        R -e 'BiocManager::install("StructuralVariantAnnotation", version="3.12")'

```
