### ISSUE TITLE
could not find function ".assertValidBreakpointGRanges"

### ISSUE THREAD

**Issue by selmapichot** [PapenfussLab/StructuralVariantAnnotation#44]
Hi, 
could you please let me know why I'm bumping into this error when I run the partner() function ? 

partner(colo829_b_gr,selfPartnerSingleBreakends=TRUE)
Error in .assertValidBreakpointGRanges(colo829_b_gr, allowSingleBreakends = selfPartnerSingleBreakends) : 
  could not find function ".assertValidBreakpointGRanges"

Many thanks.

**Comment by d-cameron** [comment]
Sounds like a versioning issue. Are you using the official BioConductor package or a `devtools::install_github` from here?

**Comment by selmapichot** [comment]
Hi, 
Many thanks for your reply. Sorted by using the Bioconductor package. 
Is there a way to list all unpartnered breakpoints found? I keep having this error "Unpartnered breakpoint found. All breakpoints must contain a partner in the breakpoint GRanges." when using the 
> mcols(gr.circos)$to.gr <- granges(partner(gr.circos)) 
But can't see any obvious unpartnered breakpoints. I have checked as well by running the `countBreakpointOverlaps` and all entries were =1

Many thanks.

**Comment by selmapichot** [comment]
I've re-installed it with the Bioconductor package, works well now. Thank you.
