### ISSUE TITLE
Fix package for installation sanity

### ISSUE THREAD

**Issue by lachlansimpson** [PapenfussLab/StructuralVariantAnnotation#5]
Currently to install, the end user must:
 - git clone http://etc sva
 - tar cxz etc.tgz sva
 - R INSTALL CMD etc.tgz

Can you please create the tgz/make a release, remove the download a zip  option (R doesn't install from zips apparently). etc.

**Comment by lachlansimpson** [comment]
Or at least provide the installation notes in the readme

**Comment by lachlansimpson** [comment]
Or add to CRAN

**Comment by d-cameron** [comment]
`devtools::install_github()` is really the only way to install until it's stable enough to include in BioConductor.

**Comment by lachlansimpson** [comment]
Thanks!

---

The most dangerous phrase in the language is, "We've always done it this
way."
- Grace Hopper
