### ISSUE TITLE
Packaged

### ISSUE THREAD

**Issue by lachlansimpson** [PapenfussLab/StructuralVariantAnnotation#7]
Any chance this could be packaged and put into CRAN or bioc?

**Comment by d-cameron** [comment]
CRAN is not appropriate as it has bioc dependencies, and the package does not yet meet the Bioconductor package guidelines. In particular, VCF object behaviour bug fixes and functionality need to be moved into the VariantAnnotation package, and the $partner GRanges breakend pairing behaviour probably needs to be replaced by an S4 class.

**Comment by d-cameron** [comment]
I know it's very late but a BioConductor submission is now in progress. 

https://github.com/Bioconductor/Contributions/issues/1079
