### ISSUE TITLE
What is the minimum length of a mutation that is annotated as a Structural Variant?

### ISSUE THREAD

**Issue by nikitagambhir** [PapenfussLab/StructuralVariantAnnotation#9]
I used GRIDSS and StructuralVariantAnnotation and I can see even 1 bp mutations in the bedpe file. If I want to change the minimum length, what would be the best route?

**Comment by d-cameron** [comment]
The default minimum size is 32bp. This can be changed by specifying a CONFIGURATION_FILE and changing/including the following line in that file:

```
variantcalling.minSize = 32
```

> I can see even 1 bp mutations in the bedpe file

GRIDSS calculates the size of an event based on to the difference between the two position of the two breakends plus the number of inserted bases. Note that this is not the same as the edit distance and an 16bp inversion will have a CIGAR of 16D16I and will be reported by the default 32bp threshold.

The 1bp events you see will either be a) insertions of least 32 bases, or b) fold-back inversions.

**Comment by nikitagambhir** [comment]
Thanks, I appreciate it! I just want to make sure that I follow you, so could you please comment on my explanation? In the following example, a piece of chromosome 1 got inserted into chromosome 4. So this can be classified as an inter-chromosomal SV (which might be a transposon movement).
<img width="744" alt="screen shot 2018-05-23 at 1 30 22 pm" src="https://user-images.githubusercontent.com/25594159/40444009-bd53df02-5e8d-11e8-87be-b9dda48e708f.png">

But in the following example, one part of chromosome 1 broke and got inserted somewhere else in the same chromosome. 
<img width="836" alt="screen shot 2018-05-23 at 1 29 45 pm" src="https://user-images.githubusercontent.com/25594159/40444364-d3159bc2-5e8e-11e8-8b83-b99b5faee71a.png">
In this case, would it be fair to call it a simple deletion or insertion? Could it be a transposon movement? If so, can we go back and trace the sequence information?
